# Take-Home Assessment 2: Creative Component

For Take-Home Assessment 2, you will write **two new coding tasks** like the ones that we gave you for the technical component. Make sure to write both **the task description** and your **working solution** (fully documented and tested)!

In [12]:
import pandas as pd
# Load the dataset with missing values
data = pd.read_csv("pokemon_missing.csv")
data

    id       name  level personality    type  weakness   atk   def   hp  stage
0  149  Dragonair     13     relaxed  dragon       ice   NaN  40.0   35    1.0
1  149  Dragonair     55       brave  dragon       ice  64.0   NaN   61    1.0
2  149  Dragonair     20       jolly  dragon       ice  35.0  60.0   45    1.0
3  149  Dragonair     31         shy  dragon       ice  55.0  41.0   45    1.0
4  147    Dratini     10      docile  dragon       ice  52.0  43.0   41    0.0
5  133      Eevee     25       naive  normal  fighting  52.0  48.0   55    0.0
6  133      Eevee     40        calm  normal  fighting  50.0   NaN  115    0.0
7  133      Eevee     35       hasty  normal  fighting  52.0  44.0   50    NaN
8  149  Dragonair     53      modest  dragon       ice  65.0  41.0   45    1.0
9  398   Staravia     28       brash  flying  electric   NaN  43.0   55    1.0

## Pokemon Sum and Min

In the technical component, you were working with a full CSV of Pokemon stats. However, while we were preparing a second CSV for you in the creative component, the staff were attacked by a [Charizard](https://pokemondb.net/pokedex/charizard) which resulted in some missing data! We need your help to fill in these values!

There are five "missing" values in `pokemon_missing.csv`. In this creative component, use `pandas` functions to fill in two of them. We are trying to have the most likely and accurate measures, so this means we can't just fill in random values. You will be able to use the rest of the data to inform your decision for what to use as a fill-in value, and how to do this. You may refer to the functions in `PandasWordbank.ipynb` for ideas.

Here's a suggested workflow:

1. Identify the 2 values you are going to fill in.
2. Explore the data to inform your choice of fill-in value.
3. Use `pandas` functions to determine the fill-in value.
4. Update the DataFrame with these values.

## Requirements

In the following code cells, use **at least 2 distinct `pandas` functions** to determine which values you will fill in. This means that each value must use a different `pandas` function! Then, explain your process and justify why you are using this particular function for that imputation.

As an example, you might choose to fill in one of the values using the `max` of some other set of values. You should tell us why you want to use the `max`, what values you are finding the `max` over, and how they relate to the missing value.

You are free to choose which functions you use for each missing value, but your solution must be presented as a **fully documented and tested function**. You are not responsible for testing with `assert` statements in this part of the THA, but you should show us the result after you have filled in your missing values.

## fill_missing_attack_with_mean

One of the missing values in the dataset is the attack (atk) stat for a Dragonair and a Staravia.
Since attack values tend to be similar within the same Pokemon species, a reasonable way to fill in a missing attack value is to use the mean attack of that species.

I use the pandas groupby and mean functions to calculate the average attack for each Pokemon name. Then, I fill in the missing attack values using that mean. This makes sense because it keeps the value realistic and consistent with the rest of the data.

In [13]:
def fill_missing_attack_with_mean(df):
    """
    Fills missing attack (atk) values using the mean attack
    of Pokemon with the same name.
    """
    mean_attack = df.groupby("name")["atk"].mean()

    df["atk"] = df["atk"].fillna(
        df["name"].map(mean_attack)
    )

    return df

In [14]:
data = fill_missing_attack_with_mean(data)
data

,id,name,level,personality,type,weakness,atk,def,hp,stage
0,149,Dragonair,13,relaxed,dragon,ice,54.75,40.0,35,1.0
1,149,Dragonair,55,brave,dragon,ice,64.00,NaN,61,1.0
2,149,Dragonair,20,jolly,dragon,ice,35.00,60.0,45,1.0
3,149,Dragonair,31,shy,dragon,ice,55.00,41.0,45,1.0
4,147,Dratini,10,docile,dragon,ice,52.00,43.0,41,0.0
5,133,Eevee,25,naive,normal,fighting,52.00,48.0,55,0.0
6,133,Eevee,40,calm,normal,fighting,50.00,NaN,115,0.0
7,133,Eevee,35,hasty,normal,fighting,52.00,44.0,50,NaN
8,149,Dragonair,53,modest,dragon,ice,65.00,41.0,45,1.0
9,398,Staravia,28,brash,flying,electric,NaN,43.0,55,1.0

## fill_missing_attack_with_mean

One of the missing values in the dataset is the attack (atk) stat for a Dragonair and a Staravia.
Since attack values tend to be similar within the same Pokemon species, a reasonable way to fill in a missing attack value is to use the mean attack of that species.

I use the pandas groupby and mean functions to calculate the average attack for each Pokemon name. Then, I fill in the missing attack values using that mean. This makes sense because it keeps the value realistic and consistent with the rest of the data.

In [15]:
def fill_missing_stage_with_min(df):
    """
    Fills missing stage values using the minimum stage
    of Pokemon with the same name.
    """
    min_stage = df.groupby("name")["stage"].min()

    df["stage"] = df["stage"].fillna(
        df["name"].map(min_stage)
    )

    return df

In [16]:
data = fill_missing_stage_with_min(data)
data

,id,name,level,personality,type,weakness,atk,def,hp,stage
0,149,Dragonair,13,relaxed,dragon,ice,54.75,40.0,35,1.0
1,149,Dragonair,55,brave,dragon,ice,64.00,NaN,61,1.0
2,149,Dragonair,20,jolly,dragon,ice,35.00,60.0,45,1.0
3,149,Dragonair,31,shy,dragon,ice,55.00,41.0,45,1.0
4,147,Dratini,10,docile,dragon,ice,52.00,43.0,41,0.0
5,133,Eevee,25,naive,normal,fighting,52.00,48.0,55,0.0
6,133,Eevee,40,calm,normal,fighting,50.00,NaN,115,0.0
7,133,Eevee,35,hasty,normal,fighting,52.00,44.0,50,0.0
8,149,Dragonair,53,modest,dragon,ice,65.00,41.0,45,1.0
9,398,Staravia,28,brash,flying,electric,NaN,43.0,55,1.0

## Submitting your work

Make sure to refer to the Take-Home Assessment 2 Guidelines for submission details. When you are submitting your notebook, make sure that the output for all cells is visible. You can do this by **running all cells** before turning in your notebook!